// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrsmmwykjibrfxblswyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yc21td3lramlicmZ4Ymxzd3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDM2NDAsImV4cCI6MjA2NDM3OTY0MH0.Hjx-YAj4rmUmaHk7fgF9SYHG_jRr8i5KsqCKdqugMbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
